//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodefluxNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsArticle
    {
        public int ArticleId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string Picture { get; set; }
        public string Url { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual NewsProvider NewsProvider { get; set; }
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
